### PR TITLE
fix: avoid an edge case that process was stubbed without process.browser property

### LINKED ISSUE #71: isNodeLike returns incorrectly in browser
**I'm submitting a bug report**

* **Library Version:**
2.3.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
10.15.3

* **NPM Version:**
6.9.0

* **JSPM OR Webpack AND Version**
webpack 4.30.0

* **Browser:**
Chrome 73.0.3683.103 | Firefox 66.0.3 | Edge 44.17763.1.0
Effectively everything I have on hand

* **Language:**
all

**Current behavior:**
Throws error as below on load
`Unhandled rejection TypeError: Unable to get property 'node-webkit' of undefined or null reference`
This is triggered by the boolean `isNodeLike` being incorrectly set to true even though the code is being executed in the browser.

Inspecting the code in browser results in a bizarre situation where the console returns a different result from the dev tools as per this screenshot.
Aurelia Bootstrapper 2019-05-03 142105

This is the same section of code that caused issues in #53 

**Expected/desired behavior:**

* **What is the expected behavior?**
Variable `isNodeLike` should return false for browsers which can be achieved which testing for the explicit process properties being subsequently used i.e.
```
const isNodeLike = typeof process !== 'undefined' && typeof process.type !== 'undefined' && typeof process.versions !== 'undefined';
```

* **What is the motivation / use case for changing the behavior?**
Code fails to execute

### PR DESCRIPTION
**Pull request by 3cp**
https://github.com/aurelia/bootstrapper/pull/72#issuecomment-2063252767

Some unknown JS lib (or browser plugin) stubbed global var "process" with only "env" property. This breaks aurelia 1's check of environment. This fix is the tiniest change I can think off. In Node(or Nodelike) environment, process.version is always populated with the version of Nodejs.

Closes #71, supersedes #72

### CODE REVIEW

**Comment by 3cp** [comment]
@berkerdemirer could you help to confirm this change bypasses the edge case?

**Comment by berkerdemirer** [comment]
Checking

**Comment by berkerdemirer** [comment]
I can confirm that this fix solves the issue.

**Comment by berkerdemirer** [comment]
Could we merge it today? @3cp

**Comment by bigopon** [comment]
Ill do a merge and release tomorrow. Thanks @3cp @berkerdemirer

**Comment by berkerdemirer** [comment]
thanks!

**Comment by bigopon** [comment]
Released in 2.4.1, thanks everyone 🙏

**Comment by berkerdemirer** [comment]
Is it possible to release it as jspm package as well?

**Pull request merged**
