### PR TITLE
Stop silently eating errors

### PR DESCRIPTION
**Pull request by patroza**
I have been running circles around myself because of swallowed errors.
This mainly affects anything directly inside, or imported into the main.js, which causes an error.
This should fix that.

However one caveat: if the logger is not configured to output anything yet, then the error won't get logged..
My workaround for that currently is System.import("config").then(() => System.import('aurelia-bootstrapper')), where config is:

```
import {LogManager} from 'aurelia-framework';
import {ConsoleAppender} from 'aurelia-logging-console';

LogManager.addAppender(new ConsoleAppender());
LogManager.setLevel(LogManager.logLevel.debug);
```

But maybe it would be better if the error could somehow be given back all the way to the aurelia-bootstrapper import?
E.g:

```
System.import("aurelia-bootstrapper")
  .then(x => x.run())
  .catch(console.error.bind(console))
```

The run function would then need to get exported, not called automatically anymore, and a Promise.all should be returned for all handleApp and readyQueue promises.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Happy to accept this. Would you mind signing our CLA? https://docs.google.com/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1  Let me know and I'll get it merged in. Thanks!

**Comment by patroza** [comment]
@EisenbergEffect of course, done!

Regarding my last comment regarding changing the bootstrapper to export a run function that should be called so you can handle the error all the way up in the index.html or whichever part that calls the bootstrapper.

I think it would be a bit more correct and clean especially considering you have to hook up the logger manually first... any feedback on that?

**Comment by EisenbergEffect** [comment]
Actually, there is a way to do that. Instead of putting an `aurelia-app` attribute  in your html, you can call the `bootstrap` function directly from your page, providing your app configuration and handling any errors.

```
System.import("aurelia-bootstrapper")
  .then(x => x.bootstrap(aurelia => {
      aurelia.use
        .standardConfiguration()
        .developmentLogging();

      aurelia.start().then(a => a.setRoot());
  }))
  .catch(console.error.bind(console))
```

**Comment by patroza** [comment]
ah great thanks!
still need to return the promise though;

```
return aurelia.start().then(a => a.setRoot());
```

**Pull request merged**
